version: '3'
services:

  backend:
    build:
      context: ../backend-node
      dockerfile: ../backend-node/Dockerfile
    ports:
      - "3000:3000"
      - "2000-2020:2000-2020"
      - "10000-10100:1000-10100"
    volumes:
      - ../backend-node/uploads:/app/uploads
    working_dir: /app

  frontend:
    build:
      context: ../frontend-solid
      dockerfile: ../frontend-solid/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ../frontend-solid:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev -- --host
